"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { type AxiosError } from "axios";
import { api, getAxiosErrorMessage, getCustomerProfile } from "@/lib/api";
import { Badge, Button, Dialog, Drawer, EmptyState, Input, LoadingSpinner, Pagination, Select } from "@/components/ui/primitives";

type Customer = { _id: string; name: string; email: string; phone: string; status: "active" | "blocked"; createdAt: string; bookingCount: number };
type CustomerDetail = Customer & { role: string; totalAmountSpent: number; bookings: Array<{ _id: string; bookingDate?: string; createdAt: string; serviceType: string; bookingStatus: string; totalAmount: number }> };
type Summary = { totalCustomers: number; activeCustomers: number; blockedCustomers: number; newCustomersThisMonth: number };
const money = (value = 0) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
const date = (value?: string) => value ? new Date(value).toLocaleDateString() : "—";

export default function AdminCustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [count, setCount] = useState(0);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [detail, setDetail] = useState<CustomerDetail | null>(null); const [confirm, setConfirm] = useState<{ customer: Customer; action: "block" | "unblock" | "delete" } | null>(null);
  const load = async () => { setLoading(true); try { const res = await api.get("/admin/customers", { params: { search, status, sort, page, limit: 10 }, headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } }); setCustomers(res.data.data); setSummary(res.data.summary); setCount(res.data.count); setError(null); } catch (caught) { setError(getAxiosErrorMessage(caught)); } finally { setLoading(false); } };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let live = true; (async () => { try { const profile = await getCustomerProfile(); if (!live) return; if (profile.user.role !== "admin") { toast.error("Access denied"); window.location.href = profile.user.role === "driver" ? "/driver/dashboard" : "/dashboard"; return; } await load(); } catch (caught) { if (live) setError(getAxiosErrorMessage(caught)); } })(); return () => { live = false; }; }, []);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 300); return () => window.clearTimeout(timer); }, [search, status, sort, page]);
  const view = async (id: string) => { setBusy(true); try { const res = await api.get(`/admin/customers/${id}`, { headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } }); setDetail(res.data.data); } catch (caught) { toast.error(getAxiosErrorMessage(caught)); } finally { setBusy(false); } };
  const act = async () => { if (!confirm) return; setBusy(true); try { const headers = { Authorization: `Bearer ${localStorage.getItem("token")}` }; if (confirm.action === "delete") await api.delete(`/admin/customers/${confirm.customer._id}`, { headers }); else await api.patch(`/admin/customers/${confirm.customer._id}/status`, { status: confirm.action === "block" ? "blocked" : "active" }, { headers }); toast.success(confirm.action === "delete" ? "Customer deleted successfully." : `Customer ${confirm.action}ed successfully.`); setConfirm(null); setDetail(null); await load(); } catch (caught) { toast.error(getAxiosErrorMessage(caught as AxiosError)); } finally { setBusy(false); } };
  const pages = Math.max(1, Math.ceil(count / 10));
  return <main className="w-full px-6 py-6"><section className="space-y-5"><div><h1 className="text-lg font-bold text-slate-900">Customers</h1><p className="mt-1 text-sm text-slate-600">Manage registered customer accounts.</p></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total Customers", summary?.totalCustomers], ["Active Customers", summary?.activeCustomers], ["Blocked Customers", summary?.blockedCustomers], ["New This Month", summary?.newCustomersThisMonth]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{loading ? "—" : value}</p></div>)}</div>
    <div className="flex flex-col gap-3 sm:flex-row"><Input placeholder="Search name, email, or phone" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /><Select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="all">All</option><option value="active">Active</option><option value="blocked">Blocked</option></Select><Select value={sort} onChange={(e) => { setSort(e.target.value); setPage(1); }}><option value="newest">Newest First</option><option value="oldest">Oldest First</option><option value="name">Name</option><option value="bookings">Total Bookings</option></Select></div>
    <div className="rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="flex items-center gap-2 p-8 text-slate-600"><LoadingSpinner />Loading customers…</div> : error ? <div className="p-5"><EmptyState title="Unable to load customers" description={error} /></div> : <><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-slate-50 text-left text-xs text-slate-600"><tr>{["Profile", "Customer Name", "Email", "Phone", "Total Bookings", "Registration Date", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{customers.map((c) => <tr key={c._id} className="border-t border-slate-100 text-sm"><td className="px-4 py-3"><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-700">{c.name.slice(0, 1).toUpperCase()}</span></td><td className="px-4 py-3 font-semibold">{c.name}</td><td className="px-4 py-3">{c.email}</td><td className="px-4 py-3">{c.phone}</td><td className="px-4 py-3">{c.bookingCount}</td><td className="px-4 py-3">{date(c.createdAt)}</td><td className="px-4 py-3"><Badge tone={c.status === "blocked" ? "red" : "green"}>{c.status}</Badge></td><td className="px-4 py-3"><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => void view(c._id)}>View</Button><Button size="sm" variant={c.status === "blocked" ? "primary" : "secondary"} onClick={() => setConfirm({ customer: c, action: c.status === "blocked" ? "unblock" : "block" })}>{c.status === "blocked" ? "Unblock" : "Block"}</Button><Button size="sm" variant="danger" onClick={() => setConfirm({ customer: c, action: "delete" })}>Delete</Button></div></td></tr>)}</tbody></table></div>{!customers.length ? <div className="p-5"><EmptyState title="No customers found" description="Try another search or filter." /></div> : <div className="flex justify-end p-4"><Pagination page={page} totalPages={pages} onPageChange={setPage} /></div>}</>}</div>
  </section><Drawer open={Boolean(detail)} title="Customer Details" onClose={() => setDetail(null)}>{detail ? <div className="space-y-4 text-sm"><p><b>Full Name:</b> {detail.name}</p><p><b>Email:</b> {detail.email}</p><p><b>Phone:</b> {detail.phone}</p><p><b>Address:</b> —</p><p><b>Role:</b> {detail.role}</p><p><b>Registration:</b> {date(detail.createdAt)}</p><p><b>Total Bookings:</b> {detail.bookingCount}</p><p><b>Total Spent:</b> {money(detail.totalAmountSpent)}</p><div><b>Booking History</b><div className="mt-2 space-y-2">{detail.bookings.map((b) => <div key={b._id} className="rounded border p-2"><p>{b._id}</p><p>{date(b.bookingDate || b.createdAt)} · {b.serviceType} · {b.bookingStatus} · {money(b.totalAmount)}</p></div>) || "No bookings"}</div></div></div> : null}</Drawer>
  <Dialog open={Boolean(confirm)} title="Confirm customer action" onClose={() => setConfirm(null)}>{confirm ? <div className="space-y-4"><p>Are you sure you want to {confirm.action} <b>{confirm.customer.name}</b>?</p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setConfirm(null)}>Cancel</Button><Button variant="danger" disabled={busy} onClick={() => void act()}>{busy ? <LoadingSpinner /> : "Confirm"}</Button></div></div> : null}</Dialog></main>;
}
